name: LoginBoxSss
main: cn.jji8.LoginBoxSss.main
version: 1.4
author: jianjianai
api-version: 1.13
commands:
  修改密码:
    aliases: [xiugaimima, xgmm]
    description: "箱子登入插件的命令"
    permission: 箱子登入.修改密码
    permission-message: "你没有权限执行此命令"
    usage: /<command>
  强制玩家重新注册:
    aliases: [qzwjcxzc, qiangziwenjiacongxingzhuche]
    description: "强制玩家重新注册"
    permission: 箱子登入.强制玩家重新注册
    permission-message: "你没有权限执行此命令"
    usage: /<command> 玩家